name: 'test my project'
on:
  push:
  pull_request:
jobs:
  test-job:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: 'setup node'
        with:
          node-version: '14.x'

      - name: 'ci'
        run: npm ci
      - name: 'prettier'
        run: npm run prettier
      - name: 'lint'
        run: npm run lint
      - name: 'test'
        run: npm run test
